apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: eks-demo
  labels:
    app: notification-service
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - name: http
      port: 80
      targetPort: 3005
      protocol: TCP
